@startuml "Class Diagram"

class Admin << Entity >> {
    + id : Number
    + name : String
    + password : String
    + email : String
    + level : Number
    + ViewCustomers()
    + ViewOrders()
}

class Customer << Entity >> {
    + id : Number
    + name : String
    + email : String
    + password : String
    + status : Number
    + Add()
    + Update()
    + Delete()
    + PlaceOrder()
}

class Market << Entity >> {
    + id : Number
    + name : String
    + locations: [Location]
}

class Category << Entity >> {
    + id : Number
    + name : String
}

class Products << Entity >> {
    + id : Number
    + catid : Number
    + name : String
    + brand : String
    + photo : String
    + notes : String
}

class Basket << Entity >> {
    + id : Number
    + customerid : Number
    + products : products[]
    + products_piece : products_piece[]
    + notes : String
    + status : Number
}

class Order << Entity >> { 
    + id : Number
    + basketid : Number
    + date : Date
}
Customer -left-o Admin
Category *-up- Market
Products *-up- Category
Customer --> Basket
Basket --> Order
Basket -left-> Market

@enduml